describe("Test components on this page",()=>{
    beforeEach(()=>{
      cy.login("string:en","superman","Admin123","Nextgen Academy")
      cy.dashboard();
    })
    it("test1-tests if the registration tile is clickable",()=>{
      cy.get('.change-location > .ng-pristine').select("Nextgen Academy")
    })
    it("test2-checks if the clinical visit button is clickable and search for a name",()=>{
      cy.get('.fa-user').click()
      cy.get('#name').type("Mukami")
      cy.get(':nth-child(4) > .reg-srch-btn > button').click()
      cy.get('tr > :nth-child(1) > a').click()
      cy.wait(10000)
    })
    it("test3-tests registration of a single client",()=>{
      cy.get('.fa-user').click()
      cy.get('.top-nav > :nth-child(3) > a > .nav-link').click()
      cy.get('#givenName').type("Jared")
      cy.get('#middleName').type("Mueni")
      cy.get('#familyName').type("Musyoka")
      cy.get('#gender').select("Other")
      cy.get('#ageYears').type("20")
      cy.get("#ageMonths").type("10")
      cy.get("#ageDays").type("3")
      cy.get('[address-fields=""] > :nth-child(1) > :nth-child(1) > .field-value > .ng-pristine').type("L. Victoria")
      cy.get('#address2').type("Kisumu")
      cy.get('#cityVillage').type("Nyando")
      cy.get('#stateProvince').type("Kisumu")
      cy.get("#country").type("Kenya")
      cy.get('#education').select("High School")
      cy.get('#occupation').select("Student")
      cy.get('#mobileNumber').type("0790657123")
      cy.get("#nationalId").type("23901765")
      cy.get("#nextOfKin").type("Horace Kimaina Kimai")
      cy.get('#nextOfKinRelationship').type("Spouse")
      cy.get("#nextOfKinContacts").type("07089346")
      cy.wait(5000)
      cy.get('strong > a').click()
      cy.get('[ng-if="section.canShow"] > .box-container > .form-field-inline > .form-field > attribute-types > .field-value').type("jayoma@intelllisoftkenay.com")
      cy.get('.submit-btn').click()
      cy.focus()
      cy.get('.toggle-button').select("Start IPD Visit visit")
    })
    it("test4-checks if the registered client is present in the system",()=>{
      cy.get('.fa-user').click()
      cy.get('#name').type("Jared")
      cy.get(':nth-child(4) > .reg-srch-btn > button').click()
      cy.get('tr > :nth-child(1) > a').click()
      cy.wait(10000)

    })
   it("test5-searches for a patient by ID",()=>{
      cy.get("#registrationNumber").type("NXG314163")
      cy.get("#subimt").click()
      
   })
})
